version: '3'

networks:
  idea2app:

services:
  web-server:
    image: idea2app/web-server
    networks:
      - idea2app
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/ || exit 1']
      interval: 3s
      retries: 5
      start_period: 30s
    labels:
      - 'autoheal=true'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 1250M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  caddy:
    depends_on:
      - web-server
    image: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - idea2app
    command: caddy reverse-proxy --from idea2app.cn --to web-server:3000
