packages:
  - .
autoInstallPeers: false
overrides:
  next: "$next"
allowBuilds:
  '@sentry/cli': true
  core-js: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - mobx-lark@2.10.0
